### ISSUE TITLE
Internet-Adressbuch statt Export/Import von XML

### ISSUE THREAD

**Issue by haumacher** [Brice187/BlockSpamCalls#1]
PhoneBlock (https://github.com/haumacher/phoneblock) stellt eine Blocklist als Internet-Adressbuch zur Verfügung. Das macht das Updaten und Eintragen von neuen Nummer viel einfacher. Außerdem kann man sich die Mühe beim Eintragen von neuen Nummer in der Community teilen. Live auszuprobieren unter: https://phoneblock.haumacher.de/

**Comment by Brice187** [comment]
Vielen Dank, das Projekt hier eh abandonware;)
